### ISSUE TITLE
DB Integration

### ISSUE THREAD

**Issue by h4n5o** [matze328/Team1_Projekt_Express#3]
Datenbankintegration.
- Express mit DB verbunden.

**Comment by matze328** [comment]
MySQL  Datenbank   
Schema :   radio_app
Tables  angelegt :   Radiosender  +  userprofiles 

Radiosender ist mit express verbunden  und läuft 
userprofiles  ist  mit express verbunden und wird noch getestet 

anbei ein Image der  MySQL  Schema :


![Image](https://github.com/matze328/Team1_Projekt/assets/152269645/66fb1c47-9421-4cab-8a04-e30905476e72)

**Comment by matze328** [comment]
und mit allen express routen verbunden  Postman Collection in documentation  geupdated
